from codenames.handlers.manage_settings.settings import settings_handler
from codenames.handlers.manage_settings.language import language_command_handler, change_language_handler
from codenames.handlers.manage_settings.nickname import nickname_handler
